on: 
  push:
    branches:
      - master
     paths:
       - 'extractCMRRPhysio/*.py'

jobs:
  publish:
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python_version}}
           
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      
      - name: tag and push
        run: |
          pwd
          ls 
          python3 --version
          python3 setup.py --version
          echo $(echo 'hello')
          git config --global user.email "yinglilu@gmail.com"
          git config --global user.name "YingLi Lu"
          git tag -a v$(python3 setup.py --version) -m "v$(python3 setup.py --version)"
          git push origin v$(python3 setup.py --version)
          
      #- name: PyPI
      #- name: Dockerhub  
