on: 
  push:
    branches:
      - master
    #paths:
    #  -'extractCMRRPhysio/version.py'

jobs:
  publish:
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python_version}}
           
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      
#       - name: tag and push
#         run: |
#           pwd
#           ls 
#           python3 --version
#           python3 setup.py --version
#           #echo ${{ echo 'hello' }}
#           #git tag -a ${{VER}} -m "${{env.VERSION}}"
#           #git push origin v${{env.VERSION}}
          
      #- name: PyPI
      #- name: Dockerhub  
