on: 
  push:
    branches:
      - master
#    paths:
#      - 'extractCMRRPhysio/version.py'

jobs:
  publish:
    strategy:
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python_version }}
           
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          which python
          which python3
          which pip
          which pip3
          
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine   
          pip install -r requirements.txt
          
      - name: Set env VERSION
        run: echo ::set-env name=VERSION::$(python3 setup.py --version)
       
      - name: git tag and push
        run: |
          echo $VERSION
          git config --global user.email "yinglilu@gmail.com"
          git config --global user.name "YingLi Lu"
          git tag -a v$VERSION -m "release v$VERSION"
          #git push origin v$VERSION
          git push -f --tags
           
      - name: PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 setup.py sdist bdist_wheel
          twine --version
          #twine upload --skip-existing dist/*
          twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*
      #- name: Dockerhub  
