on: 
  push:
    branches:
      - master
#    paths:
#      - 'extractCMRRPhysio/version.py'

jobs:
  publish:
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python_version}}
           
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      
      - name: Set env
        run: echo ::set-env name=VERSION::$(python3 setup.py --version)
       
      - name: tag and push
        run: |
          echo $VERSION
          git config --global user.email "yinglilu@gmail.com"
          git config --global user.name "YingLi Lu"
          git tag -a v$VERSION -m "release v$VERSION"
          git push origin v$VERSION
          
           
      #- name: PyPI
      #- name: Dockerhub  
