on:
  push:
    branches: 
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        python-version: [3.6,3.7,3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python_version }}

      - name: checkout
        uses: actions/checkout@v2
    
      - name: install 
        run: | 
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools pytest
          # install package
          pip3 install .

      - name: test
        run: |
          pytest ./tests
          